name: 'Release Pact Foundation Rubygem'
description: 'Bump version, generate changelog, release gem to Rubygems, create Github release notes'
runs:
  using: 'docker'
  image: 'Dockerfile'
outputs:
  gem_name:
    description: 'The name of the released gem'
  version:
    description: 'The version number of the released gem'
  tag:
    description: 'The tag of the released code'
  increment:
    description: 'The version increment of the release (minor, patch)'
