source 'https://rubygems.org'

gem 'bump', git: 'https://github.com/bethesque/bump.git'
gem 'conventional-changelog', git: 'https://github.com/bethesque/conventional-changelog-ruby.git', ref: 'feat/pact-foundation'
gem 'rake', '~>13.0'
